# This file was generated by GoReleaser. DO NOT EDIT.
cask "scl" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "61def1b6b1d3187d54180ec1dade01896429e1a655aca4071f30084eb12aa17e"
      url "https://github.com/Alai-Studios/scl-dist/releases/download/v#{version}/scl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f7db7ef84a28c92ddbf8b823ca5502a43e9d43f1a858386cd7cb04ea37fbee06"
      url "https://github.com/Alai-Studios/scl-dist/releases/download/v#{version}/scl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4e3bc147b16091942817eb6b3985f9abdf28a54925e0b496446027aa94a539e9"
      url "https://github.com/Alai-Studios/scl-dist/releases/download/v#{version}/scl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e17996fe1f8c1db661d7b8b2d45b089a025dffea575d3d2a6983183e9062cebc"
      url "https://github.com/Alai-Studios/scl-dist/releases/download/v#{version}/scl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "scl"
  desc "Spark Configuration Language — declarative provisioning for Spark organizations"
  homepage "https://github.com/Alai-Studios/scl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scl"]
    end
  end

  # No zap stanza required
end
