# This file was generated by GoReleaser. DO NOT EDIT.
cask "scl" do
  version "0.1.6"

  on_macos do
    on_arm do
      sha256 "9a43654cf88344c914e89e7e077efd4086975fc1808dc2f249914ee68c13ffa4"
      url "https://github.com/Alai-Studios/scl-dist/releases/download/v#{version}/scl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3a75c12027c4bc08e30ff7785f50e7a10c95b24b27750fa9167d38481a7d3fee"
      url "https://github.com/Alai-Studios/scl-dist/releases/download/v#{version}/scl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ec1a83e5cd1b47f17482607285a21ddca10bc004b603d7342a489133a82ba9bc"
      url "https://github.com/Alai-Studios/scl-dist/releases/download/v#{version}/scl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "806963b76c90a9e5da38db9ccc387fec04e7eac45b07525b5cab9d879a51a5c9"
      url "https://github.com/Alai-Studios/scl-dist/releases/download/v#{version}/scl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "scl"
  desc "Spark Configuration Language — declarative provisioning for Spark organizations"
  homepage "https://github.com/Alai-Studios/scl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scl"]
    end
  end

  # No zap stanza required
end
