# This file was generated by GoReleaser. DO NOT EDIT.
cask "scl" do
  version "0.1.9"

  on_macos do
    on_arm do
      sha256 "55bb61471b10cd902845599c8aafb0dcd4f47d1a523fbf82aac6ed95d433ecd9"
      url "https://github.com/Alai-Studios/scl-dist/releases/download/v#{version}/scl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ed1804ed72fddf6441b3241f1a393f77bfb855260ab6f0a0013b0f50477f4f3b"
      url "https://github.com/Alai-Studios/scl-dist/releases/download/v#{version}/scl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6df9232568334920cd330de19b108228b9fbccf66fd179df741f224f56e9e32e"
      url "https://github.com/Alai-Studios/scl-dist/releases/download/v#{version}/scl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "332e84732b91b3cf6f6e45563e173f4e3a4b8ea55c32ba6df8055ac9dd77b066"
      url "https://github.com/Alai-Studios/scl-dist/releases/download/v#{version}/scl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "scl"
  desc "Spark Configuration Language — declarative provisioning for Spark organizations"
  homepage "https://github.com/Alai-Studios/scl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scl"]
    end
  end

  # No zap stanza required
end
